apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: erp-grafana
  namespace : default
spec:
  rules:
  - host: grafana.example.com
    http:
      paths:
        - backend:
            serviceName: prometheus-grafana
            servicePort: 80
